export const UPDATE_GENERAL_INFO = 'UPDATE_GENERAL_INFO';
export const UPDATE_FCM_DEVICE_TOKEN = 'UPDATE_FCM_DEVICE_TOKEN';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const UPDATE_FCM_TOKEN_SENT_FLAG = 'UPDATE_FCM_TOKEN_SENT_FLAG';

export const CART_SELECTION_UPDATE = 'CART_SELECTION_UPDATE';
export const CART_SELECTION_CLEAR = 'CART_SELECTION_CLEAR';